"""add approved_by and submitted_to to assessments

Revision ID: e73bd471910d
Revises: a6a84d0d04aa
Create Date: 2026-09-19 11:58:29.377535

"""
from alembic import op
import sqlalchemy as sa


revision = 'e73bd471910d'
down_revision = 'a6a84d0d04aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('approved_by', sa.String(length=200), nullable=False))
    op.add_column('assessments', sa.Column('submitted_to', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'submitted_to')
    op.drop_column('assessments', 'approved_by')
    # ### end Alembic commands ###
